# Generated by Django 5.1.3 on 2024-12-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название линии')),
                ('voltage', models.CharField(choices=[('low', 'Low Voltage'), ('medium', 'Medium Voltage'), ('high', 'High Voltage')], max_length=10, verbose_name='Напряжение')),
                ('condition', models.CharField(max_length=100, verbose_name='Техническое состояние')),
                ('last_service_date', models.DateField(verbose_name='Дата последнего обслуживания')),
                ('coordinates', models.JSONField(verbose_name='Координаты линии')),
            ],
        ),
    ]
